### ISSUE TITLE
A package name are wrong

### ISSUE THREAD

**Issue by HundredGB** [mrpt-ros-pkg/mrpt_sensors#5]
An incorrect name has been registered for the ros package.
The mrpt-sensor-gnss-nmea package is registered as mrpt-sensor-gnns-nmea in the ros package.
can you fix this package name gnns->gnss?

**Comment by jlblancoc** [comment]
Thanks for reporting! 
It was fixed one month ago: 
https://build.ros2.org/job/Hbin_uJ64__mrpt_sensor_gnss_nmea__ubuntu_jammy_amd64__binary/

But it will take another humble sync release cycle to get updated apt packages...
